### ISSUE TITLE
keycloak not starting with docker-compoose

### ISSUE THREAD

**Issue by mihaimyh** [fdonnet/ubik_accounting#28]
Running `docker-compose up` and getting the following error:

```
ubik-keycloak     | Unknown option: 'start-dev'
ubik-keycloak     | Did you mean: kc.sh start-dev or kc.sh import or kc.sh start?
ubik-keycloak     | Try 'kc.sh --help' for more information on the available options.
ubik-keycloak exited with code 2
```

```
$ docker-compose -v
Docker Compose version v2.20.2-desktop.1
```
Which docker-compose version should I use?

**Comment by fdonnet** [comment]
on my side it's Docker Compose version v2.23.0-desktop.1
for you it fails on
```
  keycloak:

    command:
      - "start-dev --import-realm"
```
very strange because the entry point for keycloack seems correct
```
 entrypoint:
      - "/opt/keycloak/bin/kc.sh"
```
On my side it's working on 2 different machines

**Comment by fdonnet** [comment]
the full command is kc.sh start-dev --import-realm but I don't understand why to run it correctly. You can try to run the integration test project, it will mount the same containers but with testcontainers not with docker compose.

**Comment by fdonnet** [comment]
Ok I removed all my keycloack images and volumes etc and I have the same issue as you. I will correct and come back

**Comment by fdonnet** [comment]
Problem solved in docker compose you can pull from main 
```
  keycloak:

    command:
      - "start-dev"
      - "--import-realm"
```

Normally it will work now.
Thx for the finding... it's was working on my side with the command chained and I don't know why.

**Comment by fdonnet** [comment]
Normally you will be able to access Keycloack on:
http://localhost:8080/admin/master/console/
(admin/admin)

**Comment by fdonnet** [comment]
No feedback but tested on my side with a "clean" docker state (all keycloack imgs, volumes and containers removed) and now it works as expected.
